2024-12-19 18:42:33,810 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-12-19 18:42:33,810 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Configure stats pid to 1990781
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Loading settings from /home/hl-valdemar/.config/wandb/settings
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Loading settings from /home/hl-valdemar/Dev/Projects/University/BSc/code/src/wandb/settings
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'code/src/main.py', 'program_abspath': '/home/hl-valdemar/Dev/Projects/University/BSc/code/src/main.py', 'program': '/home/hl-valdemar/Dev/Projects/University/BSc/code/src/main.py'}
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-19 18:42:33,811 INFO    MainThread:1990781 [wandb_init.py:_log_setup():534] Logging user logs to /home/hl-valdemar/Dev/Projects/University/BSc/code/src/wandb/run-20241219_184233-wqlovx56/logs/debug.log
2024-12-19 18:42:33,812 INFO    MainThread:1990781 [wandb_init.py:_log_setup():535] Logging internal logs to /home/hl-valdemar/Dev/Projects/University/BSc/code/src/wandb/run-20241219_184233-wqlovx56/logs/debug-internal.log
2024-12-19 18:42:33,812 INFO    MainThread:1990781 [wandb_init.py:init():621] calling init triggers
2024-12-19 18:42:33,812 INFO    MainThread:1990781 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {}
2024-12-19 18:42:33,812 INFO    MainThread:1990781 [wandb_init.py:init():671] starting backend
2024-12-19 18:42:33,812 INFO    MainThread:1990781 [wandb_init.py:init():675] sending inform_init request
2024-12-19 18:42:33,824 INFO    MainThread:1990781 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-19 18:42:33,825 INFO    MainThread:1990781 [wandb_init.py:init():688] backend started and connected
2024-12-19 18:42:33,849 INFO    MainThread:1990781 [wandb_init.py:init():783] updated telemetry
2024-12-19 18:42:33,868 INFO    MainThread:1990781 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-12-19 18:42:34,235 ERROR   MainThread:1990781 [wandb_init.py:init():842] encountered error: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-19 18:42:34,235 ERROR   MainThread:1990781 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/nix/store/pca6vky6qwdp4za97lk84q9ml8mjd6ly-python3-3.12.7-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/nix/store/pca6vky6qwdp4za97lk84q9ml8mjd6ly-python3-3.12.7-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 848, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-19 18:42:34,256 WARNING MsgRouterThr:1990781 [router.py:message_loop():77] message_loop has been closed
